name: 'Arma 3 build addon'
description: 'Compile an arma 3 addon source directory into a binarized PBO file, using Arma 3 Tools'
inputs:

  source:
    description: 'Path to the addon source directory'
    required: true

  target:
    description: 'Path to the directory where the action will output the pbo file'
    required: true

  prefix:
    description: 'Prefix for the pbo file properties'
    required: true

runs:
  using: composite
  steps:

    - shell: pwsh
      run: |
        $ActionArgs = @{
          Source = Join-Path -Path ${env:GITHUB_WORKSPACE} -ChildPath '${{ inputs.source }}'
          Target = Join-Path -Path ${env:GITHUB_WORKSPACE} -ChildPath '${{ inputs.target }}'
          Prefix = '${{ inputs.prefix }}'
        }
        ${{ github.action_path }}/New-AddonPbo.ps1 @ActionArgs
